### ISSUE TITLE
Modules disnake no work!

### ISSUE THREAD

**Issue by ceedledev** [Saadelamali/Bumper-Bot#1]
<img width="482" alt="Capture" src="https://user-images.githubusercontent.com/82039844/186665916-7fa047d6-e82d-40b8-a70e-a427814e5e33.PNG">

**Comment by Saadelamali** [comment]
https://pypi.org/project/disnake/ 
thats weird tbh, try `pip install disnake` (its stupid but try it)
(sorry for late reply)

**Comment by ceedledev** [comment]
No work... 
<img width="482" alt="Capture" src="https://user-images.githubusercontent.com/82039844/187452016-679e75fe-cdeb-4c92-bd6d-bd00d816eb27.PNG">

**Comment by Saadelamali** [comment]
i dont know tbh, join their discord they'll help you 

https://discord.gg/disnake
